# Weekly Assignment #8: DPD Data

In [176]:
import pandas as pd
import altair as alt

## Reading in the Denver policing data for November

In [219]:
all_data_df = pd.read_csv("Denver policing data November 2020 .csv")
all_data_df

,raw_row_number,date,time,location,lat,lng,district,precinct,type,disposition,arrest_made,citation_issued,warning_issued,outcome
0,1,2012-11-13,00:02:22,8500 W CRESTLINE AVE,39.618329,-105.092691,4,423,vehicular,K - Street Check Completed,False,False,False,NaN
1,16,2012-11-29,00:25:01,8500 W CRESTLINE AVE,39.618329,-105.092691,4,423,vehicular,Party Advised,False,False,False,NaN
2,72,2012-11-23,22:58:10,4830 S HOLLAND WAY,39.630666,-105.102551,4,423,vehicular,K - Street Check Completed,False,False,False,NaN
3,121,2012-11-27,17:48:33,4885 S QUEBEC ST,39.626174,-104.904062,3,324,pedestrian,In Service,False,False,False,NaN
4,138,2012-11-14,23:46:58,W LAYTON AVE / S WADSWORTH BLVD,39.630150,-105.081693,4,423,vehicular,Party Advised,False,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6360,672025,2012-11-06,00:03:34,E 56TH AVE / N TOWER RD,39.798303,-104.772121,5,522,vehicular,T - Citation Issued,False,True,False,citation
6361,672116,2012-11-09,07:33:48,5300-BLK N PEORIA ST,39.792865,-104.847131,5,511,vehicular,Warning Issued,False,False,True,warning
6362,672283,2012-11-28,15:57:42,E RANDOLPH PL / N WORCHESTER ST,39.797568,-104.830744,5,521,vehicular,Party Advised,False,False,False,NaN
6363,672463,2012-11-29,20:37:09,E 55TH AVE / E MAXWELL PL,39.794786,-104.749367,5,523,vehicular,Warning Issued,False,False,True,warning
6364,672589,2012-11-23,20:43:49,E 51ST AVE / N QUENTIN ST,39.789289,-104.844671,5,521,vehicular,"Vehicle Towed,Warning Issued",False,False,True,warning

## Filters data by date

In [220]:
precinct_gb = all_data_df.groupby(pd.Grouper(key='date'))

## Aggregates the data by the total number of arrests made each day of November

In [221]:
agg_d = {'arrest_made':['sum']}
daily_arrests_df = precinct_gb.agg(agg_d)
daily_arrests_df = daily_arrests_df.sort_values(by='date')
daily_arrests_df

           arrest_made
                   sum
date
2012-11-01          44
2012-11-02          56
2012-11-03          36
2012-11-04          21
2012-11-05          25
2012-11-06          29
2012-11-07          26
2012-11-08          36
2012-11-09          23
2012-11-10          21
2012-11-11          40
2012-11-12          36
2012-11-13          44
2012-11-14          40
2012-11-15          32
2012-11-16          39
2012-11-17          43
2012-11-18          21
2012-11-19          30
2012-11-20          36
2012-11-21          30
2012-11-22          17
2012-11-23          39
2012-11-24          47
2012-11-25          27
2012-11-26          20
2012-11-27          27
2012-11-28          29
2012-11-29          36
2012-11-30          35

#### Data Manipulation [for formatting purposes]

In [222]:
daily_arrests_df = daily_arrests_df.reset_index(level=[0])
dates_df = daily_arrests_df['date'].to_frame()
merged_daily_arrests_df = dates_df.join(daily_arrests_df['arrest_made']).rename(columns={"sum": "# of Arrests", "date": "Date"})
merged_daily_arrests_df

          Date  # of Arrests
0   2012-11-01            44
1   2012-11-02            56
2   2012-11-03            36
3   2012-11-04            21
4   2012-11-05            25
5   2012-11-06            29
6   2012-11-07            26
7   2012-11-08            36
8   2012-11-09            23
9   2012-11-10            21
10  2012-11-11            40
11  2012-11-12            36
12  2012-11-13            44
13  2012-11-14            40
14  2012-11-15            32
15  2012-11-16            39
16  2012-11-17            43
17  2012-11-18            21
18  2012-11-19            30
19  2012-11-20            36
20  2012-11-21            30
21  2012-11-22            17
22  2012-11-23            39
23  2012-11-24            47
24  2012-11-25            27
25  2012-11-26            20
26  2012-11-27            27
27  2012-11-28            29
28  2012-11-29            36
29  2012-11-30            35

## Data Visualization

In [226]:
alt.Chart(merged_daily_arrests_df).mark_bar().encode(y='# of Arrests', x='Date').properties(title='Denver Arrest Frequency in November of 2012')

alt.Chart(...)

In [227]:
alt.Chart(merged_daily_arrests_df).mark_bar().encode(y='# of Arrests', x='Date').properties(title='Denver Arrest Frequency in November of 2012')